### PR TITLE
🔨: change to hatch

### PR DESCRIPTION
**Pull request by nstarman**
With hatch + src I've never needed any of the `_dev` or other layers of backup.

### CODE REVIEW

**Review by neutrinoceros — COMMENTED** [review]
Awesome ! I was wondering if it was possible to replace `setuptools_scm` in hatch so thanks for showing the way !
My one question is: does `hatchling` respect. `MANIFEST.in` ? I got the impression that it was a `setuptools` specific thing and that migrating to hatchling in general required listing some `include` / `exclude` list in `pyproject.toml` instead.

**Comment by nstarman** [comment]
A good Q. Not so sure. I haven't inspected my packages...

**Comment by nstarman** [comment]
Ok. Just took a look at `https://pypi.org/project/unxt/` by unpacking the tar.gz and yeah it seems to include the whole repo. Probably want to fix that!

**Comment by nstarman** [comment]
Looks like we want something like: 
```
include = [
    "README.md",
    "LICENSE",
    "src/**/*.py"
]
```

**Comment by nstarman** [comment]
@mhvk @neutrinoceros what do we want / need to include?

**Comment by neutrinoceros** [comment]
`.gitignore` is already taken into account and I don't see anything else that needs to be included/excluded explicitly here.

**Review by mhvk — APPROVED** [review]
OK, I checked and this works fine with `tox` also locally, so I'm happy to proceed. Two small things I noticed:
- there are a few `_dev` mentions in `pyproject.toml` that can now be removed.
- given that very little is left of the openastronomy installation, we can probably remove `.cruft.json`

I just pushed this directly to your branch.

**Pull request merged**
